#!/bin/bash -e

AWS=$(which aws)

function usage {
  echo "USAGE: $0 <region> <keyname>"
  echo "  example: $0 us-west-1 my_key_pair"
  exit 1
}

if [ -z "$1" ] || [ -z "$2" ]; then
  usage
fi

region="${1}"
keyname="${2}"
pem="${keyname}.pem"

if ${AWS} --region ${region} ec2 describe-key-pairs --key-name ${keyname} > /dev/null 2>&1 ;
then
  echo "key pair ${keyname} already exists."
  exit 1
fi

echo "Creating keypair ${keyname} in ${region}"
${AWS} --region ${region} ec2 create-key-pair \
  --key-name ${keyname} \
  --output text \
  --query 'KeyMaterial' \
  > ${pem}
chmod 600 ${pem}
